FROM golang:1.25.1 AS builder
WORKDIR /sqlcode
ENV GODEBUG="x509negativeserial=1"
COPY . .
RUN go mod tidy
# Skip the example folder because it has examples of what-not-to-do
CMD ["go", "test", "-v", "$(go list ./... | grep -v './example')"]